var Units;
if (typeof parent.Units !== 'undefined') Units = parent.Units;
else Units = new function () {


	this.minify = function () {

	};

	this.build = function () {
		Debug.open();
		Debug.msg('Сборка юнитов...');

		var c = JSON.parse(Fs.read_file(Project.path+Fs.delm+'config.json'));
		var r = '// Generated by NW.js IDE';

		_for(c['units'], function (u) {
			Debug.msg('Обработка: '+u);
			r += '\n\n//UNIT '+u+'\n'+Fs.read_file(Project.path+Fs.delm+u).toString();
		});

		Debug.msg('Генерация: '+c['name']);
		Fs.write_file(Project.path+Fs.delm+c['name'], r);

		Files.update();
	};
};